name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - preview

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
